version: "3"
services:

  grafana:
    image:          grafana/grafana
    # build: .
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    networks:
      - tig

  influxdb:
    image:          influxdb:latest
    container_name: influx
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb
    networks:
      - tig

  telegraf:
    container_name: telegraf
    image:          telegraf
    volumes:
      - ./telegraf/conf/telegraf.conf:/etc/telegraf/telegraf.conf
    networks:
      - tig

networks:
  tig:
    driver: bridge
