grafana:
  image: grafana/grafana:latest
  container_name: grafana
  ports:
    - "3000:3000"
  # env:
  links:
    - influxdb
  volumes:
    - ./grafana/data:/var/lib/grafana

influxdb:
  image: influxdb:latest
  container_name: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
# env:
  volumes:
    - ./influxdb/data:/var/lib/influxdb
  restart: always
  # 
  # telegraf:
  #   container_name: telegraf
  #   image: telegraf
  #   network_mode: "host"
  #   volumes:
  #     - ./telegraf/conf/telegraf.conf:/etc/telegraf/telegraf.conf
  #     # - /var/run/docker.sock:/var/run/docker.sock
